# Generated by Django 5.2.2 on 2025-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cardetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('car_name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('car_types', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('mpv', 'MPV')], max_length=30)),
                ('geartype', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('fueltype', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid'), ('ev', 'Electric (EV)')], max_length=20)),
                ('seating', models.IntegerField(choices=[(5, '5 Seater'), (7, '7 Seater')])),
                ('fastag', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], max_length=20)),
                ('features', models.ManyToManyField(blank=True, to='adminapp.feature')),
            ],
        ),
    ]
