# Generated by Django 5.1.6 on 2025-07-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='features',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='car_types',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='model_year',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='carname',
            field=models.CharField(default='demoName', max_length=100),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='cartype',
            field=models.CharField(default='suv', max_length=20),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='modelyear',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='availability',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='fueltype',
            field=models.CharField(default='petrol', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='geartype',
            field=models.CharField(default='automatic', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='seating',
            field=models.CharField(default=5, max_length=10),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
