# Generated by Django 5.2.2 on 2025-07-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_cardetails_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='carname',
            field=models.CharField(default='Car name', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='fueltype',
            field=models.CharField(default='Petrol', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='geartype',
            field=models.CharField(default='Automatic', max_length=10),
        ),
    ]
