# Generated by Django 5.2.2 on 2025-07-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_cardetails_carname_alter_cardetails_fueltype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='features',
        ),
    ]
