# Generated by Django 5.1.6 on 2025-07-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_cardetails_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cardetails')),
            ],
        ),
    ]
