# Generated by Django 5.1.6 on 2025-07-14 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default='Tamil Nadu', max_length=225),
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='customername',
            field=models.CharField(default='customer nmae', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
