# Generated by Django 5.1.6 on 2025-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_booking_address_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='licenceimage',
            field=models.ImageField(blank=True, null=True, upload_to='Licence/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='licencenumber',
            field=models.CharField(default='NA12345678', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobilenumber',
            field=models.BigIntegerField(default=9999999999),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(default='Tamil Nadu', max_length=225),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customername',
            field=models.CharField(default='customer name', max_length=100),
        ),
    ]
