# Generated by Django 5.1.6 on 2025-07-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_booking_email_booking_licenceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobilenumber',
            field=models.BigIntegerField(default=9999999999, max_length=10),
        ),
    ]
