# Generated by Django 5.1.6 on 2025-07-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_booking_mobilenumber'),
        ('user', '0002_alter_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.signup'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobilenumber',
            field=models.BigIntegerField(default=9999999999),
        ),
    ]
