# Generated by Django 5.1.6 on 2025-07-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_booking_drop_datetime_booking_pickup_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='cust',
        ),
    ]
