# Generated by Django 5.1.6 on 2025-07-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_rename_user_booking_cust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cust',
            new_name='user',
        ),
    ]
