# Generated by Django 5.1.6 on 2025-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='carname',
            field=models.CharField(default='Car name', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='car_snapshots/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
