# Generated by Django 5.1.6 on 2025-07-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_rename_image1_booking_car_image_booking_cartype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cartype',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='fueltype',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='geartype',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seating',
        ),
    ]
