# Generated by Django 5.1.6 on 2025-07-31 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_booking_cartype_remove_booking_fueltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
