# Generated by Django 5.1.6 on 2025-07-16 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_booking_status'),
        ('user', '0002_alter_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='customer name', max_length=100)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('mobilenumber', models.BigIntegerField(default=9999999999)),
                ('licencenumber', models.CharField(default='NA12345678', max_length=10)),
                ('licenceimage', models.ImageField(blank=True, null=True, upload_to='Licence/')),
                ('address', models.CharField(default='Tamil Nadu', max_length=225)),
                ('bookingdate', models.DateField(default=datetime.date.today)),
                ('pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('drop_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('CarDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cardetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
            ],
        ),
    ]
