# Generated by Django 5.1.6 on 2025-07-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_booking_cartype_remove_booking_fueltype_and_more'),
        ('user', '0003_cancelledbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledbooking',
            name='car_image1',
            field=models.ImageField(blank=True, null=True, upload_to='cancelled_car_images/'),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='carname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='CarDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.cardetails'),
        ),
    ]
