# Generated by Django 5.1.6 on 2025-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_cancelledbooking_car_image1_cancelledbooking_carname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledbooking',
            name='car_image1',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
