# Generated by Django 5.1.6 on 2025-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_cancelledbooking_car_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledbooking',
            name='car_image1',
            field=models.ImageField(blank=True, null=True, upload_to='car_snapshots/'),
        ),
    ]
