# Generated by Django 5.1.6 on 2025-07-31 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_cancelledbooking_car_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
